Fix request 1 block when block_process_limit is 1
safe-global/safe-transaction-service pull request #1239
Opened 2022-12-19 17:52 UTC by moisses89

Closes #1238

2022-12-21 15:55 UTC, Uxio0 commented on safe_transaction_service/history/indexers/ethereum_indexer.py
> +        if self.block_process_limit == 1:
I would propose removing this and just:

```
 return min(
            from_block_number + self.block_process_limit - 1,
            current_block_number - self.confirmations,
)
```

2022-12-21 16:00 UTC, Uxio0 commented on safe_transaction_service/history/indexers/ethereum_indexer.py
> +        if self.block_process_limit == 1:
Oh i get it, then we will never index the last block. Could you add a test for this so we don't break it in the future?

2022-12-21 16:44 UTC, Uxio0 requested changes
This implementation will break the indexer, as indexer will not increase the `to_block_number` and will keep looping in the same block.

We should refactor the code where is needed so `get_to_block_number` can be:

```
 return min(
            from_block_number + self.block_process_limit - 1,
            current_block_number - self.confirmations,
)
```

I added a test that should pass

2022-12-30 14:30 UTC, moisses89 commented
> This implementation will break the indexer, as indexer will not increase the `to_block_number` and will keep looping in the same block.
> 
> We should refactor the code where is needed so `get_to_block_number` can be:
> 
> ```
>  return min(
>             from_block_number + self.block_process_limit - 1,
>             current_block_number - self.confirmations,
> )
> ```
> 
> I added a test that should pass

I think that there is an issue in this part of code:
```
    def get_block_numbers_for_search(
        self, addresses: Sequence[str], current_block_number: Optional[int] = None
    ) -> Optional[Sequence[Tuple[int, int]]]:
        """
        :param addresses:
        :param current_block_number: To prevent fetching it again
        :return: Minimum common `from_block_number` and `to_block_number` for search of relevant `tx hashes`
        """
        current_block_number = (
            current_block_number or self.ethereum_client.current_block_number
        )

        common_minimum_block_number = self.get_minimum_block_number(addresses)
        if common_minimum_block_number is None:  # Empty queryset
            return None

        from_block_number = common_minimum_block_number + 1
        if (from_block_number + self.block_process_limit) >= (
            current_block_number - self.confirmations
        ):
            # Reindex again when it's almost synced to prevent reorg/missing elements issues
            from_block_number = max(from_block_number - self.blocks_to_reindex_again, 0)

        if (current_block_number - common_minimum_block_number) <= self.confirmations:
            return  # We don't want problems with reorgs

        to_block_number = self.get_to_block_number(
            from_block_number, current_block_number
        )
        return from_block_number, to_block_number
```
For example imagine that we define:
```
block_process_limit = 10
blocks_to_reindex = 10
current_block_number = 19
```
The first cycle go from block 1 to block 10.
Second cycle: 
- common_minimum_block_number = 10 
- from_block_number at this point is 11 because `common_minimum_block_number (10) + 1 `
- because from_block_number (11) + block_process_limit (10) > current_block_number (19) then 
  from_block_number is equals to 1 at this point.
- then get_to_block_number is 10 again because  `from_block_number(1) + block_process_limit (10)  -1 `
And again second cycle starts in 1 and ends in 10...
This is not related with `get_to_block_number` because would happen the same if  `blocks_to_reindex = 11` and with the old implementation. 
Then this happen always that `get_to_block_number` is equals to  `blocks_to_reindex`

2023-01-17 15:04 UTC, Uxio0 requested changes

2023-01-17 15:04 UTC, Uxio0 commented on safe_transaction_service/history/indexers/ethereum_indexer.py
> +            if self.blocks_to_reindex_again >= self.block_process_limit:
Please add tests for this

2023-01-17 15:19 UTC, Uxio0 commented on safe_transaction_service/history/indexers/ethereum_indexer.py
> +            if self.blocks_to_reindex_again >= self.block_process_limit:
Also I'm a little worried that if `block_process_limit` is too tight we can miss reindexing some transactions, but I think there's no easy solution for that

2023-01-30 10:38 UTC, moisses89 commented
Currently we are not having a lot of issues we the reindex blocks and I'm not feeling confident with this PR, but we should try to find a way to down to one block in the indexer.

2023-01-30 10:38 UTC, closed without merging