Add kava (testnet and mainnet) to setup_service and price_service
safe-global/safe-transaction-service pull request #1261
Opened 2023-01-09 14:38 UTC by pkakelas

### Make sure these boxes are checked! 📦✅

- [ 👍] You ran `./run_tests.sh`
- [👍 ] You ran `pre-commit run -a`
- [👍 ] If you want to add your network to `setup_service.py`, provide a link to your
    [safe-deployments PR](https://github.com/safe-global/safe-deployments/pulls) and check network name
    exists in [safe-eth-py](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py)
    - https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py#L261
    - https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py#L381
    - https://github.com/safe-global/safe-deployments/pull/145
    - https://github.com/safe-global/safe-deployments/pull/137

2023-01-13 12:56 UTC, moisses89 requested changes

2023-01-13 12:56 UTC, moisses89 commented on safe_transaction_service/history/management/commands/setup_service.py
> +    EthereumNetwork.KAVA_EVM: [
`KAVA_EVM_MAINNET` is preferable to be aligned with the other chain names.

2023-01-13 12:56 UTC, moisses89 commented on safe_transaction_service/history/management/commands/setup_service.py
> +        ("0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552", 2241523, "1.3.0"),
In this block only have one transaction to create the proxyFactory. Then I couldn't confirm that this contracts were deployed at this block. 
https://explorer.testnet.kava.io/block/2241523/transactions#txs

2023-01-30 11:10 UTC, moisses89 commented on safe_transaction_service/history/management/commands/setup_service.py
> +    EthereumNetwork.KAVA_EVM: [
This is ok, it's the same name that is in safe-eth-py.

2023-03-07 13:49 UTC, Uxio0 commented
I'm closing this as it's inactive

2023-03-07 13:49 UTC, closed without merging