support meter network for token price fetching
safe-global/safe-transaction-service pull request #1617
Opened 2023-08-11 18:14 UTC by simonzg

### What was wrong? 👾

Price fetching for tokens on meter network is not supported, including native token and asset token with address.
The fallback price fetching seems not right with 
`self.get_token_usd_price(token_address) / self.get_ether_usd_price`

### How was it fixed? 🎯

For native token price, register meter network in `get_token_eth_price_from_oracles` to fetch MTR price with coingecko client.

For token address, there's no compatible oracles on meter network, so I configured the fallback price fetching with coingecko.

The fallback price should be `self.get_token_usd_price(token_address) / self.get_native_coin_usd_price()`

2023-08-11 20:06 UTC, simonzg commented
I have read the CLA Document and I hereby sign the CLA

2023-08-17 08:08 UTC, moisses89 requested changes
Could you include your test here? https://github.com/safe-global/safe-transaction-service/blob/master/safe_transaction_service/tokens/tests/test_price_service.py#L67C9-L67C39
Thanks for your contribution.

2023-08-17 08:08 UTC, moisses89 commented on safe_transaction_service/tokens/clients/coingecko_client.py
> +        EthereumNetwork.METER_TESTNET: "meter"
Could you remove testnet asset?

2023-08-22 16:47 UTC, simonzg commented on safe_transaction_service/tokens/clients/coingecko_client.py
> +        EthereumNetwork.METER_TESTNET: "meter"
testnet is now removed

2023-08-22 16:48 UTC, simonzg commented on safe_transaction_service/tokens/services/price_service.py
> +            or self.get_token_usd_price(token_address) / self.get_native_coin_usd_price()
got it, thanks

2023-08-23 17:18 UTC, simonzg commented
Added test case as requested.

2023-08-24 08:54 UTC, moisses89 approved these changes

2023-08-28 14:36 UTC, Uxio0 commented
@simonzg please fix linting

2023-08-28 14:37 UTC, Uxio0 requested changes
@simonzg please fix linting. Tests are not passing either

2023-08-30 12:39 UTC, Uxio0 approved these changes

2023-08-30 12:39 UTC, merged

2023-08-30 12:39 UTC, Uxio0 commented
Thanks for your PR!