Adds management command for inserting safe master copy
safe-global/safe-transaction-service pull request #1785
Opened 2023-11-30 08:19 UTC by peterpolman

### Make sure these boxes are checked! 📦✅

- [ ] You ran `./run_tests.sh`
- [ ] You ran `pre-commit run -a`
- [ ] If you want to add your network to `setup_service.py`, provide a link to your
    [safe-deployments PR](https://github.com/safe-global/safe-deployments/pulls) and check network name
    exists in [safe-eth-py](https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/ethereum_network.py)

### What was wrong? 👾
There was no programmatic way available to easily insert a SafeMasterCopy address into the database. This made it cumbersome to run txs in an isolated CI environment with a local node and Safe contracts were used to test against. 

Closes https://github.com/safe-global/safe-infrastructure/issues/102

### How was it fixed? 🎯
Added a python management command for inserting the mastercopy address into the database, allowing for programmatic insert of SafeMasterCopy objects.

2023-11-30 08:23 UTC, peterpolman commented
Not able to run local tests due to an issue `building wheel for psycopg2` during install. Probably environment specific problem as my machine doesn't run python projects often.

```shell
Using cached pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
Building wheels for collected packages: psycopg2
  Building wheel for psycopg2 (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [149 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-13-arm64-cpython-311
      creating build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/_json.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/extras.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/errorcodes.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/tz.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/_range.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/_ipaddress.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/__init__.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/extensions.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/errors.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/sql.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      copying lib/pool.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
      running build_ext
      building 'psycopg2._psycopg' extension
      creating build/temp.macosx-13-arm64-cpython-311
      creating build/temp.macosx-13-arm64-cpython-311/psycopg
      clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall "-
      ...
      ...
      ...
      ...
      ...
      ld: library not found for -lssl
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for psycopg2
  Running setup.py clean for psycopg2
Failed to build psycopg2
ERROR: Could not build wheels for psycopg2, which is required to install pyproject.toml-based projects
```

2023-12-01 13:23 UTC, moisses89 commented
> Not able to run local tests due to an issue `building wheel for psycopg2` during install. Probably environment specific problem as my machine doesn't run python projects often.
> 
> ```shell
> Using cached pyasn1-0.5.1-py2.py3-none-any.whl (84 kB)
> Building wheels for collected packages: psycopg2
>   Building wheel for psycopg2 (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py bdist_wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [149 lines of output]
>       running bdist_wheel
>       running build
>       running build_py
>       creating build
>       creating build/lib.macosx-13-arm64-cpython-311
>       creating build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/_json.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/extras.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/errorcodes.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/tz.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/_range.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/_ipaddress.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/__init__.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/extensions.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/errors.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/sql.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       copying lib/pool.py -> build/lib.macosx-13-arm64-cpython-311/psycopg2
>       running build_ext
>       building 'psycopg2._psycopg' extension
>       creating build/temp.macosx-13-arm64-cpython-311
>       creating build/temp.macosx-13-arm64-cpython-311/psycopg
>       clang -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall "-
>       ...
>       ...
>       ...
>       ...
>       ...
>       ld: library not found for -lssl
>       clang: error: linker command failed with exit code 1 (use -v to see invocation)
>       error: command '/usr/bin/clang' failed with exit code 1
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
>   ERROR: Failed building wheel for psycopg2
>   Running setup.py clean for psycopg2
> Failed to build psycopg2
> ERROR: Could not build wheels for psycopg2, which is required to install pyproject.toml-based projects
> ```

Hey thanks for your PR. 
Taking a look to your issue you are missing system dependencies, take a look how to install them. 
About your PR, I would like to have a test about the command and also could you include the proxy factories?

2023-12-01 14:24 UTC, peterpolman commented
@moisses89 Alright alright, I managed to google and fix it😉 First time pythoners on MacOs Sillicon might run into this install issue as well. If so, fix it with an alias for your openssl lib. This assumes you install(ed) openssl using brew:
```bash
brew install openssl 
export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/opt/openssl/lib
pip install -r requirements.txt
```
> and also could you include the proxy factories?
Sure! Similar command for inserting a `ProxyFactory` object and it's props or a single command for both addresses? It didn't seem required in my local setup, so I have not worked with it directly. Should I have?😅

2023-12-04 09:57 UTC, Uxio0 requested changes
Thanks for your contribution! Remember to also sign the NDA

2024-03-05 22:21 UTC, peterpolman commented
I have read the CLA Document and I hereby sign the CLA

2025-03-04 22:27 UTC, closed without merging