Fix SafeRelevantTransaction default timestamp
safe-global/safe-transaction-service pull request #2347
Opened 2024-11-27 15:04 UTC by falvaradorodriguez

2024-11-27 15:15 UTC, moisses89 requested changes

2024-11-27 15:15 UTC, moisses89 commented on safe_transaction_service/history/indexers/tx_processor.py
> +                    defaults={"timestamp": ethereum_tx.block.timestamp},
It is the related field included in the queryset ethereum_tx?
If not this will create a new request to database for each ethereum_tx.

2024-11-27 15:19 UTC, Uxio0 requested changes

2024-11-27 15:19 UTC, Uxio0 commented on safe_transaction_service/history/indexers/tx_processor.py
> +                    defaults={"timestamp": ethereum_tx.block.timestamp},
```suggestion
                    defaults={"timestamp": internal_tx.timestamp},
```

2024-11-27 15:19 UTC, Uxio0 commented on safe_transaction_service/history/indexers/tx_processor.py
> +                    defaults={"timestamp": ethereum_tx.block.timestamp},
```suggestion
                    defaults={"timestamp": internal_tx.timestamp},
```

2024-11-27 15:19 UTC, Uxio0 commented on safe_transaction_service/history/indexers/tx_processor.py
> +                    defaults={"timestamp": ethereum_tx.block.timestamp},
`timestamp` for `internal_tx` should be the same of the block (it's denormalized on the database for optimizing some queries). That way we save a database call to get the `block` for every `ethereum_tx`

2024-11-28 10:19 UTC, Uxio0 approved these changes

2024-11-28 12:06 UTC, moisses89 approved these changes

2024-11-28 12:28 UTC, merged