Only reindex singletons/events if service is synced
safe-global/safe-transaction-service pull request #2348
Opened 2024-11-27 15:13 UTC by Uxio0

2024-11-28 09:13 UTC, falvaradorodriguez approved these changes

2024-11-28 09:55 UTC, moisses89 requested changes

2024-11-28 09:55 UTC, moisses89 commented on safe_transaction_service/history/tasks.py
> +                )
Should be a return here?

2024-11-28 09:55 UTC, moisses89 commented on safe_transaction_service/history/tasks.py
> +                )
Should be a return here? and I also would add a return at the end of the task.

2024-11-29 11:42 UTC, Uxio0 commented on safe_transaction_service/history/tasks.py
> +                )
Done

2024-12-03 16:15 UTC, moisses89 approved these changes

2024-12-03 16:16 UTC, merged