Add smartBCH contracts, configure price service to fetch prices
safe-global/safe-transaction-service pull request #869
Opened 2022-05-27 07:13 UTC by mainnet-pat

- Add smartbch deployments
- Support fetching bch price
- Add price service configuration for smartbch
- Add mistswap price oracle, change bch usd price ticker on coingecko to wrapped-bch
- smartBCH deployments using safe singleton factory

### What was wrong?

N/A

Closes #

N/A

### How was it fixed?

Added new safe deployment info from smartBCH

@gnosis/safe-services

2022-05-27 07:20 UTC, mainnet-pat commented
I have read the CLA Document and I hereby sign the CLA

2022-05-27 08:57 UTC, Uxio0 commented
Related to https://github.com/safe-global/safe-deployments/pull/90

2022-06-07 15:07 UTC, Uxio0 requested changes

2022-06-07 15:07 UTC, Uxio0 commented on safe_transaction_service/tokens/services/price_service.py
> +class MistswapOracle(UniswapV2Oracle):
Oracles should go in https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/oracles/oracles.py

2022-06-30 13:36 UTC, mainnet-pat commented
Hey, yes, sorry for not having time to finish it. I'd need to update the oracle repository first.

2022-07-22 08:07 UTC, closed without merging